### ISSUE TITLE
[Android TV] NVIDIA Shield TV (2015)

### ISSUE THREAD

**Issue by KingNothing81** [redphx/better-xcloud-devices#1]
### Checklist

- [X] I will only use English
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud-devices/issues?q=is%3Aissue) to see if someone else has already submitted the same device
- [X] I put device name in the issue's title (example: **`[Android] Google Pixel 8`**)

### Device name

NVIDIA Shield TV - 2015 version (P2571)

### Debug info

![IMG_0273](https://github.com/user-attachments/assets/cb9a8b37-fe13-4fb5-8411-3910ac939446)
![IMG_0274](https://github.com/user-attachments/assets/a2c51c5c-2957-49f4-91d4-a4257747c98c)
![IMG_0275](https://github.com/user-attachments/assets/6bff6608-258e-4eb4-a15f-81ea6c29b8eb)

### WebView

Default

### App settings

- [ ] Hardware Back button as Xbox button
- [ ] Optimize WebView performance

**Comment by KingNothing81** [comment]
Some additional notes:

The Shield TV was refreshed two times by Nvidia (2017 & 2019). My device is the initial version released 2015. But only the 2019 version has an updated Tegra X1+ chip that may show other results.

https://en.m.wikipedia.org/wiki/Nvidia_Shield_TV

My Shield TV (2015) handles 1080p@High with unlimited bitrate without issues. And in my opinion the performance with the current version of the default "Android System WebView" is so good now, that users don't need to enable the WebView optimizations and/or install another WebView. I tried that, but without noticing a significant difference. So I ended up always using the default WebView now, since it will get automatic updates over the PlayStore. And I'm really satisfied with the performance.

But what doesn't work on my Shield TV (2015) is using the "WebGL2" renderer. Enabling it makes the stream very choppy and xCloud unusuable. I also tried to make it work with other WebViews (Chrome, Thorium), with/without the Webview optimizations enabled and tried all "GPU configuration" settings. But it didn't make a difference. Maybe the situation is different on the 2019 version, but for the previous versions the "WebGL2" renderer shouldn't be recommended.

The “Sharpness” setting is also very much about personal preference in my opinion. I have it set to "Off" most of the times, as my TV already has an "enhanced sharpness" option that I use. But if users have to use  "Unsharp Masking", I wouldn't suggest going higher than level 2, as the effect is stronger than with "AMD CAS".

Hope this helps.
Thanks.

**Comment by redphx** [comment]
Update the beta script and try again. Thanks.

<img width="429" alt="image" src="https://github.com/user-attachments/assets/068891ac-b27b-4bca-914e-77f6933c6c72">

**Comment by KingNothing81** [comment]
Hi ...

Thanks for the update.

Just some additional thoughts:

- When using the default renderer, the "Renderer Configuration" option is hidden in the UI. So does it even matter, what it's set to when not using "WebGL2"? Because in my debug info I saw that it was still on "High Performance" from the last time I tried out "WebGL2". But for using the default renderer, this option will have no effect, right?

- And instead of recommending to turn "touch controller availablity" off, how about suggesting the "Android TV" profile for devices like the Shield TV? Because this will disable touch and also hide the touch controller options in the UI.

Thanks.

**Comment by KingNothing81** [comment]
Hi …

I can confirm now that the suggest feature correctly identifies my device as “Shield TV (2015)” and applies the suggested settings correctly.

But one thing I noticed is that the ‘highest quality” profile is missing. So if it’s not intended behavior to hide it when there is a device specific profile, I guess I discovered a bug?

**Comment by redphx** [comment]
The `highest quality` profile will be hidden on devices that have `recommended` profile
